version: "3.9"
name: "road_vision__database"
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      db_network:

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      db_network:

  store:
    container_name: store
    build: ..
    depends_on:
      - postgres_db
    restart: always
    environment:
      RUST_BACKTRACE: 1
      RUST_LOG: DEBUG
    volumes:
      - ./store/logs:/app/logs
      - ../configuration:/app/configuration
    ports:
      - "8080:8080"
    networks:
      db_network:

networks:
  db_network:

volumes:
  postgres_data:
  pgadmin_data:
